import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import { ReactNode, unstable_SuspenseList } from "react";
import { locales } from '@/navigation';
import { notFound } from 'next/navigation';
import {unstable_setRequestLocale} from 'next-intl/server'
import LanguageChanger from "@/components/LanguageChanger";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type Props = {
  children: ReactNode,
  params: { locale: string },
};

export function generateStaticParams() {
  return locales.map((locale) => ({ locale }));
}

export default function RootLayout({
  children,
  params: { locale },
}: Props){
  if (!locales.includes(locale as any)) notFound();
  unstable_setRequestLocale(locale);

  return (
    <html lang={locale}>
      <body className={inter.className}>
        <LanguageChanger locale={locale} />
        {children}
      </body>
    </html>
  );
}
